version: '{branch}-{build}'

skip_tags: true

image: Visual Studio 2019
configuration: Debug

environment:
  nodejs_version: 12
  GH_TOKEN:
    secure: LoVmzGA7T3XhMSo95dA8juWRXXkBB7wvqCt0PwlXQM1f3dCdkTnHO18Ax42eUgex

skip_commits:
  files:
    - '.gitignore'
    - '*.md'
    - 'docs/*'
    
before_build:
  - nuget restore
  - nuget install OpenCover -OutputDirectory packages -Version 4.6.519
  - choco install codecov

build:
  project: Sophia.sln
  verbosity: minimal

test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:administrator -target:"dotnet.exe" -targetargs:"test Sophia.Tests\bin\Debug\netcoreapp3.1\Sophia.Tests.dll" -output:"coverage.xml" -filter:"+[Sophia*]* -[Sophia.Tests*]*"
  - codecov -f "coverage.xml"

before_package:
- ps: .\BuildUnityPackages.ps1

artifacts:
- path: '*.unitypackage'
- path: '*Sophia*\bin\Debug\*\*Sophia*'

cache: '%APPDATA%\npm'

install:
- ps: >-

    Install-Product node $env:nodejs_version



    npm install -g semantic-release


deploy_script:
- semantic-release