version: '{branch}-{build}'

skip_tags: true

image: Visual Studio 2019
configuration: Release

environment:
  nodejs_version: 12
  GH_TOKEN:
    secure: LoVmzGA7T3XhMSo95dA8juWRXXkBB7wvqCt0PwlXQM1f3dCdkTnHO18Ax42eUgex

skip_commits:
  files:
    - '.gitignore'
    - '*.md'

before_build:
  - nuget restore
build:
  project: Sophia.sln
  verbosity: minimal

before_package:
- ps: .\BuildUnityPackages.ps1

artifacts:
- path: '*.unitypackage'

deploy:
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: LoVmzGA7T3XhMSo95dA8juWRXXkBB7wvqCt0PwlXQM1f3dCdkTnHO18Ax42eUgex

cache: '%APPDATA%\npm'

install:
- ps: >-

    Install-Product node $env:nodejs_version



    npm install -g semantic-release


deploy_script:
- semantic-release