version: '{branch}-{build}'

skip_tags: true

image: Visual Studio 2019
configuration:
    - Debug
    - Release

environment:
  nodejs_version: 12
  GH_TOKEN:
    secure: LoVmzGA7T3XhMSo95dA8juWRXXkBB7wvqCt0PwlXQM1f3dCdkTnHO18Ax42eUgex

skip_commits:
  files:
    - '.gitignore'
    - '*.md'
    - 'docs/*'
    
before_build:
  - nuget restore

build:
  project: Sophia.sln
  verbosity: minimal


before_package:
- ps: .\BuildUnityPackages.ps1

artifacts:
- path: '*.unitypackage'

matrix:
  fast_finish: true

for:
-
  matrix:
    only:
      - configuration: Debug
  before_build:
   - nuget install OpenCover -OutputDirectory packages -Version 4.7.922
   - choco install codecov
  artifacts:
   - path: '*Sophia*\bin\Debug\*\*Sophia*'
  test_script:
   - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -returntargetcode -register -target:"dotnet.exe" -targetargs:"vstest Sophia.Tests\bin\Debug\netcoreapp3.1\Sophia.Tests.dll" -output:"coverage.xml" -filter:"+[Sophia*]* -[Sophia.Tests*]*"
   - codecov -f "coverage.xml"
-
  matrix:
    only:
      - configuration: Release
  artifacts:
  - path: '*Sophia*\bin\Release\*\*Sophia*'
  cache:
   - '%APPDATA%\npm'
  install:
   - ps: Install-Product node $env:nodejs_version
   - npm install -g semantic-release
  deploy_script:
   - semantic-release