name: Run Unity tests
on: [push, pull_request]
jobs:
  first_job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            lfs: true
      - name: Test project
        uses: webbertakken/unity-test-runner@v1.4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: /
          unityVersion: 2019.3.0f6
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}